# Generated by Django 3.2.6 on 2021-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210817_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
